name: Merge to staging

on:
  workflow_dispatch:

jobs:
  merge-branch:
    name: Merge branch
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create pull request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: development
        destination_branch: staging
        pr_title: Merge development branch
        pr_body: Deploy started manually.
        pr_allow_empty: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
